### ISSUE TITLE
OpenMP RUN_TESTS fails

### ISSUE THREAD

**Issue by dlparkhurst** [usgs-coupled/phast3#14]
I compiled the Release configuration of phast for openmp without a problem. RUN_TESTS fails. I tried running CMake-gui and VS from a git bash shell, a OneAPI shell, and an Anaconda prompt, but got the following error each time.

Build started...
1>------ Build started: Project: RUN_TESTS, Configuration: Release x64 ------
1>1>
1>Test project C:/Users/David/Downloads/Install/20240626/archive/WWW/PHAST/phast-3.8.0-16905/_build_openmp
1>    Start 1: phastinput.phrqex11
1>1/2 Test #1: phastinput.phrqex11 ..............   Passed    0.06 sec
1>    Start 2: phast.phrqex11
1>2/2 Test #2: phast.phrqex11 ...................Exit code 0xc0000139
1>***Exception:   0.04 sec
1>
1>50% tests passed, 1 tests failed out of 2
1>
1>Total Test time (real) =   0.12 sec
1>
1>The following tests FAILED:
1>	  2 - phast.phrqex11 (Exit code 0xc0000139
1>)
1>Errors while running CTest
1>Output from these tests are in: C:/Users/David/Downloads/Install/20240626/archive/WWW/PHAST/phast-3.8.0-16905/_build_openmp/Testing/Temporary/LastTest.log
1>Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: The command "setlocal
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: "C:\Program Files\CMake\bin\ctest.exe" --force-new-ctest-process -C Release
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: :cmEnd
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: :cmErrorLevel
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: exit /b %1
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: :cmDone
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: :VCEnd" exited with code 8.
1>Done building project "RUN_TESTS.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
========== Build started at 9:35 PM and took 00.714 seconds ==========

I can't find any error message that indicates why phast failed.

I am able to install phast in a directory (INSTALL), and then use the files in INSTALL/bin to run phastinput and phast without a problem.

**Comment by scharlton2** [comment]
I think when running RUN_TESTS that it's not finding the openmp dll.  I can't remember what it's called.  I think that when it's installed the openmp dll is copied into the bin directory.  You could try running dumpbin on the built exe to check it's dependencies using:

`dumpbin /dependents src\phast\Release\phast3.exe`

I'll see if I can get the test to work by either copying the dll or modifying the path for the test

**Comment by dlparkhurst** [comment]
I can now run the tests. I think I had a 32-bit OneAPI prompt and an error in my path.
